Create Json model "Address"
it-kmitl-2018/group7 pull request #75
Opened 2018-05-07 16:04 UTC by noxusfrosted

- Create AddressJsonConverter class
- Create JsonConverter test
- Add lombok dependency

2018-05-08 03:37 UTC, champillon reviewed
ไม่เห็น test สร้าง Json เลย

2018-05-13 09:39 UTC, noxusfrosted commented
@champillon เพิ่ม Test ให้แล้วช่วยดูให้หน่อยครับ

2018-05-13 11:52 UTC, champillon approved these changes

2018-05-13 15:17 UTC, keattiwut requested changes
ไม่ให้ผ่านครับ ยังตั้งชื่อ Class สับสน context อยู่ครับ รบกวนไปแก้มาใหม่

2018-05-13 15:35 UTC, noxusfrosted commented
@keattiwut แก้แล้วนะครับช่วยตรวจสอบให้หน่อยครับ

2018-05-13 16:14 UTC, keattiwut approved these changes

2018-05-14 04:29 UTC, merged

2018-05-20 17:10 UTC, champillon commented
1.75 คะแนน