create TaxpayerIdCode
it-kmitl-2018/group7 pull request #85
Opened 2018-05-13 05:38 UTC by smarty0123

2018-05-13 05:41 UTC, champillon reviewed
แก้มาหน่อย

2018-05-13 05:41 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group7/definitions/TaxpayerIdCode.java
> +public enum TaxpayerIdCode {
มันควรเป็น TaxPayerIdCode สิ camel-case สิ

2018-05-13 05:50 UTC, champillon reviewed
แก้มาหน่อย

2018-05-13 05:50 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group7/definitions/TaxPayerIdCode.java
> +    TaxPayerIdCode(String taxpayerIdCode, String nameTh, String nameEn) {
ชื่อ parameter ตัวแรกด้วยสิ

2018-05-13 06:08 UTC, smarty0123 commented
@champillon เรียบร้อยครับ

2018-05-13 06:41 UTC, champillon approved these changes
LGTM ก็ได้

2018-05-13 06:46 UTC, keattiwut requested changes
enum ตัวนี้ ถ้าจะ มีแต่ code น้องจะ map มาเป็น enum ยังไงครับ?

2018-05-13 09:41 UTC, smarty0123 commented
@keattiwut แก้แล้วครับ

2018-05-13 15:05 UTC, keattiwut approved these changes

2018-05-14 04:17 UTC, merged

2018-05-14 04:24 UTC, keattiwut reviewed
เพิ่ม code เพิ่ม test ด้วยเจ้าาา

2018-05-20 17:08 UTC, champillon commented
1.75 คะแนน