Create json model "Note"
it-kmitl-2018/group7 pull request #95
Opened 2018-05-13 09:47 UTC by noxusfrosted

Create json model "Note"

2018-05-13 11:53 UTC, champillon approved these changes

2018-05-13 15:20 UTC, keattiwut requested changes
ยังสับสนใจ context ของ Converter ไปแก้มาหน่อยครับ

2018-05-13 15:35 UTC, noxusfrosted commented
@keattiwut แก้แล้วนะครับช่วยตรวจสอบให้หน่อยครับ

2018-05-13 16:14 UTC, keattiwut approved these changes

2018-05-14 04:28 UTC, merged

2018-05-20 17:10 UTC, champillon commented
1.25 คะแนน